### ISSUE TITLE
Version 1.30, the plugin is perfect! But I have a small problem, the "after_detailer" doesn't work.

### ISSUE THREAD

**Issue by cdmusic2019** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#334] opened 2023-07-18 10:41 UTC
Plugin version 1.3, I have installed adetailer, but in PS it says "Script is not available". Is there something I haven't installed in the right place?
![01](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/126891037/5ab82b7f-34bb-4b0d-98b9-242686498dd9)
![02](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/126891037/892bc40a-0475-4d56-9028-8609a4667e7d)
![03](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/126891037/75658190-e1ce-423e-bbaf-b6f88c8739ac)

**Comment by AbdullahAlfaraj** [comment] 2023-07-18 10:53
Will release a quick update to fix this issue.
The issue caused by Adetialer changing their internal script name from 'After Detailer' to “Adetailer” and so the plugin can’t tell if the script is installed or not.
You can revert to previous version of ADetiler like the one in this screenshot:

![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/ee6ea26d-f70d-4a7d-96d8-412b64597507)

**Comment by cdmusic2019** [comment] 2023-07-18 10:57
Thank you. That's great.

**Comment by RaXorX** [comment] 2023-07-27 03:57
Any updates on this?

**Comment by AbdullahAlfaraj** [comment] 2023-08-04 13:45
The issue has been fixed in https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/pull/348/commits/fd134ef7b261e1fa4897d2725593f9d93303cd4f . For method 1(.ccx), method 2(.zip) users you will need to wait a bit longer till I release v1.3.1

**Comment by mongalong247** [comment] 2023-09-09 04:42
Is this updated in 1.3.1? I am getting the error message still.  Definitely on 1.3.1

**Comment by zombieyang** [comment] 2023-09-09 07:41
> Is this updated in 1.3.1? I am getting the error message still. Definitely on 1.3.1

Oops I don't know this one. 1.3.1 is just for Controlnet fix. We will publish it maybe 1.4.0 or 1.3.2

**Closed** 2023-09-12 10:28 UTC
Labels: Auto1111 Issue, bug, Fixed: Awaiting .ccx Update
